-- =====================================================
-- URGENT ROLLBACK: Restore deleted charmbar categories
-- Created: 2026-07-03
-- Purpose: Restore all categories that were accidentally deleted
-- =====================================================

-- Temporarily allow inserting specific IDs
ALTER TABLE retail_categories ALTER COLUMN id SET GENERATED BY DEFAULT;

-- Restore all old charmbar categories
INSERT INTO retail_categories (id, department, name, slug, parent_id, is_active, created_at) VALUES
  (26, 'charmbar', 'BASIC', 'basic', NULL, false, '2026-06-07 04:24:09.143101+00'),
  (5, 'charmbar', 'EDGY SOUL', 'edgy-soul', NULL, true, '2026-06-04 10:11:41.925617+00'),
  (6, 'charmbar', 'FOODIE', 'foodie', NULL, true, '2026-06-04 10:11:49.929001+00'),
  (54, 'charmbar', 'General / Other', 'charmbar-general-auto', NULL, false, '2026-06-30 07:26:39.342933+00'),
  (4, 'charmbar', 'HOBBY', 'hobby', NULL, true, '2026-06-04 10:11:35.255666+00'),
  (3, 'charmbar', 'HOLIDAY', 'holiday', NULL, true, '2026-06-04 10:11:27.209338+00'),
  (7, 'charmbar', 'ISLAND VIBES', 'island-vibes', NULL, true, '2026-06-04 10:12:11.898053+00'),
  (39, 'charmbar', 'Jewelry', 'charmbar-jewelry', NULL, false, '2026-06-12 07:51:49.121891+00'),
  (8, 'charmbar', 'LOVE', 'love', NULL, true, '2026-06-04 10:12:25.04842+00'),
  (21, 'charmbar', 'LUCKY-CHARM', 'lucky-charm', NULL, true, '2026-06-06 16:02:03.57674+00'),
  (9, 'charmbar', 'PETS', 'pets', NULL, true, '2026-06-04 10:12:30.519486+00'),
  (10, 'charmbar', 'POP ICON', 'pop-icon', NULL, true, '2026-06-04 10:12:42.273711+00'),
  (92, 'charmbar', 'Satuan Charm', 'charmbar-satuan-charm', NULL, true, '2026-07-01 07:44:49.38963+00'),
  (11, 'charmbar', 'SKY DREAM', 'sky-dream', NULL, true, '2026-06-04 10:12:50.233515+00'),
  (12, 'charmbar', 'SOFT MUSE', 'soft-muse', NULL, true, '2026-06-04 10:12:56.551586+00'),
  (13, 'charmbar', 'THE ICON', 'the-icon', NULL, true, '2026-06-04 10:13:04.52078+00'),
  (14, 'charmbar', 'ZODIAC', 'zodiac', NULL, true, '2026-06-04 10:13:11.737046+00'),
  (91, 'charmbar', 'Base', 'base', 21, true, '2026-07-01 03:24:53.368569+00'),
  (33, 'charmbar', 'pendants', 'pendants', 21, true, '2026-06-11 09:43:50.788549+00'),
  (34, 'charmbar', 'welded', 'welded', 21, true, '2026-06-11 09:45:04.493451+00')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  slug = EXCLUDED.slug,
  parent_id = EXCLUDED.parent_id,
  is_active = EXCLUDED.is_active,
  created_at = EXCLUDED.created_at;

-- Restore to GENERATED ALWAYS
ALTER TABLE retail_categories ALTER COLUMN id SET GENERATED ALWAYS;

-- Verify restoration
SELECT COUNT(*) as restored_categories
FROM retail_categories
WHERE department = 'charmbar';
